import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from "../components/header/header";
import Calendar from "../components/calendar/calendar";

const Home: NextPage = () => {
  return (
    <div className={'max-w-7xl m-auto'}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className={'flex xl:flex-row flex-col p-5 gap-10'}>
          <div className="basis-1/2">
              <Calendar/>
          </div>
          <div className={'basis-1/2 xl:p-0 p-10'}>Hello</div>
      </main>

    </div>
  )
}

export default Home
